In [1]:
import torch
import pandas as pd
import numpy as np

# Introduction to Tensors

### Creating tensors

In [2]:
# Scalar
scalar  = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.item()

7

In [4]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [5]:
print(vector.ndim)
vector.shape

1


torch.Size([2])

In [6]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [7]:
print(MATRIX.ndim)
MATRIX.shape

2


torch.Size([2, 2])

In [8]:
MATRIX[0]

tensor([7, 8])

In [9]:
# Tensors
Tensor  = torch.tensor([[[1,2],
                        [3, 4],
                        [5, 6]]])
Tensor

tensor([[[1, 2],
         [3, 4],
         [5, 6]]])

In [10]:
Tensor.ndim
Tensor.shape

torch.Size([1, 3, 2])

## Random Tensors

In [11]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)

In [12]:
random_tensor

tensor([[0.4087, 0.9161, 0.2037, 0.8322],
        [0.2753, 0.2375, 0.1967, 0.7121],
        [0.4950, 0.7886, 0.7115, 0.8620]])

In [13]:
random_tensor.ndim

2

In [14]:
random_tensor.shape

torch.Size([3, 4])

In [15]:
# Create a random tensor with similar shape to an image tensor
random_img_size_tensor = torch.rand(size=(224, 224, 3))
random_img_size_tensor.shape, random_img_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Zeros and Ones

In [16]:
# create a tensor of all zeros 
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [17]:
# Create tensors of ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [18]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [19]:
# Use torch.range()
one_to_ten = torch.arange(start=1, end=11, step=2)
one_to_ten

tensor([1, 3, 5, 7, 9])

In [20]:
# Create tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0])

## Tensor datatypes

In [21]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None,
                            device=None,
                            requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [22]:
float_32_tensor.dtype

torch.float32

In [23]:
float_16_tensor = float_32_tensor.type(torch.float16)

In [24]:
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [25]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

### Getting infromation from tensors

In [26]:
some_tensor = torch.rand(3, 4)
some_tensor = some_tensor.type(torch.float64)

In [27]:
some_tensor.size(), some_tensor.shape

(torch.Size([3, 4]), torch.Size([3, 4]))

In [28]:
some_tensor.device

device(type='cpu')

### Manipulating Tensors (tensor operations)

Tensor Operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [29]:
# Creating a tensor
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# Multiply tensor
tensor * 10

tensor([10, 20, 30])

tensor([10, 20, 30])

In [ ]:
tensor - 10

tensor([-9, -8, -7])

In [ ]:
# Try out Pytorch inbuilt functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Find the positional in tensor that has minimum value with agrmin()